version: "3"
services:
  awscli-utils:
    image: mikesprague/cloud-utils:latest
    container_name: cloud-utils
    environment:
      # configures awscli-login for Cornell use
      # (if false, all tools are still available - awscli-login simply not auto-configured)
      - SETUP_AWSCLI_LOGIN=true
      # next 3 options only matter if SETUP_AWSCLI_LOGIN is true
      # options are: push, sms, phone, auto
      - DUO_FACTOR="auto"
      # don't change this unless you're sure you have another endpoint and have the correct URL
      - ECP_ENDPOINT="https://shibidp.cit.cornell.edu/idp/profile/SAML2/SOAP/ECP"
      # add your netid (leaving blank will simply prompt you for username when you run aws login)
      - NETID=""
      # installs zsh, oh-my-zsh, and enables plugins (aws, git, zsh-suggestions, zsh-completions)
      # starts your session in a zsh terminal versus bash
      - SETUP_OHMYZSH=false
      # installs fx json viewer, nodejs, and npm
      # fx is a powerful jq alternative - https://github.com/antonmedv/fx/
      - SETUP_FX=false
      # installs terraform and enables terraform autocomplete from cli
      # pins terraform version to number specified or grabs latest if none
      - SETUP_TERRAFORM=true
      - TERRAFORM_VERSION=0.11.13
    networks:
      - default
    stdin_open: true
    tty: true
    volumes:
      - ./:/mounted-home
      - ${HOME}/.aws:/root/.aws
      - ${HOME}/.aws-login:/root/.aws-login
    working_dir: "/mounted-home"
    command: [ "/bin/bash" ]
networks:
  default:
    driver: "bridge"
