version: "3"
services:
  awscli-utils:
    image: mikesprague/awscli-utils:latest
    container_name: awscli-utils
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_PROFILE=default
      - ECP_ENDPOINT=https://shibidp.cit.cornell.edu/idp/profile/SAML2/SOAP/ECP
      - NETID=abc123 # change to your netid
    networks:
      - default
    stdin_open: true
    tty: true
    volumes:
      - ./:/mounted-home
      - ${HOME}/.aws:/root/.aws
      - ${HOME}/.aws-login:/root/.aws-login
    working_dir: "/mounted-home"
    command: bash -c "setup-awscli-login && bash"
networks:
  default:
    driver: "bridge"
